- hosts: "localhost"
  tasks:
           - name: Downloading Docker Repo
             yum_repository:
                     name: Docker
                     description: docker_repo
                     baseurl: https://download.docker.com/linux/centos/8/x86_64/stable
                     gpgcheck: no


           - package:
                     name: "docker-ce-18.09.1-3.e17.x86_64"
                     state: present

           - name: Starting Docker
             service:
                     name: "docker"
                     state: started
                     enabled: yes

           - name: downloading python dependencies
             pip:
                     name: docker

           - name: Creating a folder
             file:
                     path: "/mydoc"
                     state: directory

           - name: copying webserver files
             copy:
                     src: "home.html"
                     dest: "/mydoc/"

           - name: starting httpd webserver using Docker
             docker_container:
                     name: "webserver"
                     image: httpd
                     state: started
                     exposed_ports:
                     - "/80"
                     volumes:
                     - /mydoc:/usr/local/apache2/htdocs/


